import fs from "fs";
import path from "path";

const VAULT_ROOT = "c:/Users/isaqu/OneDrive/Documentos/Obsidian/ObsidianNeural/Obyron Neural/Obyron";

function getDepth(dirPath: string): number {
    const rel = path.relative(VAULT_ROOT, dirPath);
    if (!rel) return 0; // Root is Obyron
    return rel.split(path.sep).length;
}

function processDirectory(dirPath: string) {
    if (!fs.existsSync(dirPath)) return;
    
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    
    const childrenNames: string[] = [];
    
    // Subdirectories
    const dirs = entries.filter(e => e.isDirectory());
    for (const d of dirs) {
        childrenNames.push(d.name);
        // Process recursively
        processDirectory(path.join(dirPath, d.name));
    }
    
    // Markdown files (excluding the MOC file itself)
    const folderName = path.basename(dirPath);
    const mdFiles = entries.filter(e => e.isFile() && e.name.endsWith(".md") && e.name !== `${folderName}.md`);
    
    for (const f of mdFiles) {
        childrenNames.push(f.name.replace(".md", ""));
    }
    
    // Generate MOC file
    if (folderName !== "Obyron" || true) { // We can generate Obyron.md too
        const mocPath = path.join(dirPath, `${folderName}.md`);
        
        const rel = path.relative(VAULT_ROOT, dirPath);
        const parts = rel ? rel.split(path.sep) : [];
        const depth = getDepth(dirPath) + 1;
        
        const hierarchyTags = ["obyron", ...parts.map(p => p.toLowerCase().replace(/\s+/g, "-")), `nivel/${depth}`];
        const uniqueTags = Array.from(new Set(hierarchyTags));
        const tagsStr = uniqueTags.join(", ");
        const cssClass = uniqueTags[1] || uniqueTags[0] || "obyron";
        
        // Remove duplicate entries
        const uniqueChildren = Array.from(new Set(childrenNames)).sort();
        const links = uniqueChildren.map(c => `- [[${c}]]`).join("\n");
        
        let existingContent = "";
        if (fs.existsSync(mocPath)) {
            existingContent = fs.readFileSync(mocPath, "utf-8");
        }
        
        // If it's a completely new file or generated by us
        const content = `---
tags: [${tagsStr}]
cssclass: folder-${cssClass}
---
# ${folderName}

Nó pai gerado automaticamente.

## Conteúdos e Conexões
${links}
`;
        
        fs.writeFileSync(mocPath, content, "utf-8");
        console.log(`Generated MOC for ${folderName} at ${mocPath}`);
    }
}

console.log("Starting sync...");
processDirectory(VAULT_ROOT);
console.log("Sync complete!");
